# Generated by Django 2.2.6 on 2019-11-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
