# Generated by Django 2.2.6 on 2019-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191115_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
