# Generated by Django 2.2.6 on 2019-11-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caisse',
        ),
        migrations.DeleteModel(
            name='FormCommande',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Temoignage',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
