# Generated by Django 2.2.6 on 2019-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0003_caisse_categorie_formcommande_newsletter_panier_produit_profile_temoignage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
