# Generated by Django 2.2.6 on 2019-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0005_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categories',
        ),
        migrations.AlterField(
            model_name='panier',
            name='produit',
            field=models.ManyToManyField(related_name='produitPanier', to='agri.Produit'),
        ),
    ]
