# Generated by Django 2.2.6 on 2019-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0006_auto_20191118_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='forme',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
